const mongoose = require('mongoose')

const totalsSchema = mongoose.Schema({
  totalcat: String,
  cats: {
    siamese: Number,
    burmese: Number,
    ragdoll: Number,
    persian: Number,
    mainecoon: Number,
    russianblue: Number,
    calico: Number,
    tabby: Number,
    abyssinian: Number,
    manx: Number,
    sphynx: Number,
    cyprus: Number,
    foldex: Number,
    turkishangora: Number,
    norwegianforest: Number,
    devonrex: Number,
    korat: Number,
    singapura: Number,
    tonkinese: Number,
    peterbald: Number,
    chartreux: Number,
    munchkin: Number,
    britishshorthair: Number,
    ojosazules: Number,
    bandit: Number,
    bug: Number,
    linda: Number,
    mittens: Number,
    cash: Number,
    jackson: Number,
    cottonball: Number,
    sonny: Number,
    smokey: Number,
    lailah: Number,
    cher: Number,
    marvin: Number,
    loki: Number,
    loverboy: Number,
    killerclaws: Number,
    squirtlett: Number,
    cursedcat: Number,
    uwu: Number,
    tom: Number,
    demoncat: Number,
    bongocat: Number,
    grumpycat: Number,
    ghostcat: Number
  }
})

module.exports = mongoose.model('totalList', totalsSchema)
